name: Terraform Deployment to Azure

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.tf'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Set Azure Credentials as Env Vars
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CREDENTIALS.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CREDENTIALS.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_CREDENTIALS.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_CREDENTIALS.AZURE_TENANT_ID }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init
        
      - name: Debug env
        run: env | grep ARM_
      
      - name: Terraform Import Resource
        run: terraform import azurerm_resource_group.example "/subscriptions/80ea84e8-afce-4851-928a-9e2219724c69/resourceGroups/813-11ca4b41-hands-on-with-terraform-on-azure"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

